name: Hyperion
version: '${project.version}'
main: me.vermeil.hyperion.Hyperion
api-version: '1.20'
load: STARTUP
authors: [VermeilChan]
description: Hyperion is a Spigot plugin inspired by the Hyperion abilities from the Hypixel Skyblock.
website: https://github.com/VermeilChan/Hyperion
commands:
  givehyperion:
    usage: /givehyperion
    description: Gives the Hyperion item to the player.
permissions:
  hyperion.give:
    default: true
    description: Allows players to use the /givehyperion command.